name: drift_tx_bug
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  drift: ^2.15.0
  drift_postgres: ^1.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  postgres: ^3.0.8

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  drift_dev: ^2.15.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
